### ISSUE TITLE
BUG: 使用 PATCH 方法执行请求连接超时

### ISSUE THREAD

**Issue by developerworks** [mpflutter/mpflutter_build_tools#1]
缺少 PATCH 方法

https://github.com/mpflutter/mpflutter_build_tools/blob/933e119e8ef9f74c7e75623d5950985a60a3d889/wechat_flutter_js/flutter_bom/xml-http-request.js#L12

列表里面没有 PATCH, XMLHttpRequest.open 方法直接返回, 导致连接超时
<img width="1288" alt="image" src="https://github.com/mpflutter/mpflutter_build_tools/assets/725190/9816d680-3271-45fd-969a-848bfa0f68c0">

<img width="976" alt="image" src="https://github.com/mpflutter/mpflutter_build_tools/assets/725190/14c0f4b2-d154-47dc-b3ab-cfe10e3d49f5">

**Comment by PonyCui** [comment]
根据微信文档显示，request 方法是不支持 PATCH 的。
https://developers.weixin.qq.com/miniprogram/dev/api/network/request/wx.request.html

**Comment by developerworks** [comment]
但是我确实把 PATCH 加到 `SUPPORT_METHOD` 数组里面编译后正常运行呢

**Comment by developerworks** [comment]
建议在 `return;` 之前加一个日志, 这个困扰了我好久才找到问题所在

**Comment by PonyCui** [comment]
感谢建议，PATCH 已经添加到 SUPPORT_METHOD 中。
